title: Chinatip Lawansuk
email: l.chinatip@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal Page
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chinatip-l.github.io" # the base hostname & protocol for your site

